In [2]:
import pandas as pd

# Load datasets
ae_df = pd.read_csv("hyperparameter_results/ae_gridsearch_results.csv")
tabgan_df = pd.read_csv("hyperparameter_results/tabgan_gridsearch_run_results.csv")

# Best 4 AE results: smallest best_val_loss
best_ae = ae_df.sort_values("best_val_loss", ascending=True).head(4)

# Best 4 TabGAN results: largest mean_total_score
best_tabgan = tabgan_df.sort_values("mean_total_score", ascending=False).head(4)

print("Best 4 AE results")
display(best_ae)

print("\nBest 4 TabGAN results")
display(best_tabgan)

Best 4 AE results

,run_name,best_epoch,best_val_loss,test_loss,input_dim,latent_dim,hidden_dims,dropout,batch_size,learning_rate,weight_decay
0,ae_ld8_hd256-128_bs64_lr5e-05_do0.0_wd0.0,49,0.000010,0.000011,6,8,"(256, 128)",0.0,64,0.00005,0.00000
1,ae_ld8_hd64-32_bs128_lr0.001_do0.0_wd0.0,47,0.000011,0.000012,6,8,"(64, 32)",0.0,128,0.00100,0.00000
2,ae_ld8_hd256-128_bs64_lr5e-05_do0.0_wd1e-05,38,0.000011,0.000012,6,8,"(256, 128)",0.0,64,0.00005,0.00001
3,ae_ld8_hd256-128_bs128_lr0.0001_do0.0_wd0.0,45,0.000013,0.000014,6,8,"(256, 128)",0.0,128,0.00010,0.00000

Best 4 TabGAN results

,run_name,mean_total_score,merged_output_path,gen_x_times,pregeneration_frac,is_post_process,bot_filter_quantile,top_filter_quantile,use_adversarial,batch_size,patience,epochs
55,run_051_gxt1.5_preg3_post1_bs128_pat20_ep100_b...,0.039815,tabgan_gridsearch_runs/synthetic_outputs/run_0...,1.5,3,True,0.001,0.999,False,128,20,100
54,run_052_gxt1.5_preg3_post1_bs128_pat20_ep200_b...,0.039815,tabgan_gridsearch_runs/synthetic_outputs/run_0...,1.5,3,True,0.001,0.999,False,128,20,200
50,run_020_gxt1.0_preg3_post1_bs128_pat20_ep200_b...,0.036147,tabgan_gridsearch_runs/synthetic_outputs/run_0...,1.0,3,True,0.001,0.999,False,128,20,200
51,run_019_gxt1.0_preg3_post1_bs128_pat20_ep100_b...,0.036147,tabgan_gridsearch_runs/synthetic_outputs/run_0...,1.0,3,True,0.001,0.999,False,128,20,100

In [ ]:
s